spring:
  application:
    name: recipe-catalog-scanner
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  mvc:
    problemdetails:
      enabled: true

server:
  error:
    include-stacktrace: never
    include-message: never

ollama:
  num-ctx: 16384
